### ISSUE TITLE
Doesn't work with Django 1.10

### ISSUE THREAD

**Issue by Flimm** [bartgryszko/django-absoluteurl#2]
When trying to use this template tag with Python 3.6 and Django 1.10, I get this error:

> Invalid template library specified. ImportError raised when trying to load 'absoluteurl.templatetags.absoluteurl': cannot import name 'RequestSite'

I think this is because newer Django versions require importing `RequestSite` from `django.contrib.sites.requests`.
